create table Products (
	ID INT,
	Name VARCHAR(50),
	Description VARCHAR(50),
	Price VARCHAR(50),
	Remarks VARCHAR(50),
	Category VARCHAR(50)
);
insert into Products (ID, Name, Description, Price, Remarks, Category) values (1, 'healthy accents cough relief', 'Superficial foreign body, right lower leg, initial encounter', '€154,82', 'Late effect of complications of surgical and medical care', 'Anastomosis to anus');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (2, 'La Roche Posay Laboratoire Dermatologique Anthelios 50 Mineral Body Broad Spectrum SPF 50 Ultra Light Sunscreen', 'Perforation due to foreign body accidentally left in body following endoscopic examination, initial encounter', '€171,59', 'Other closed skull fracture without mention of intracranial injury, unspecified state of consciousness', 'Other bilateral endoscopic destruction or occlusion of fallopian tubes');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (3, 'kirkland signature cold', 'Subluxation of midcarpal joint of right wrist', '€78,97', 'Sprain of cruciate ligament of knee', 'Transjugular liver biopsy');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (4, 'Loratadine and Pseudoephedrine Sulfate', 'Unspecified injury of other blood vessels at abdomen, lower back and pelvis level, initial encounter', '€59,03', 'Calculus of lower urinary tract, unspecified', 'Manual testing of muscle function');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (5, 'Joint Pain', 'Non-pressure chronic ulcer of unspecified part of right lower leg', '€122,72', 'Blister of other, multiple, and unspecified sites, without mention of infection', 'Closure of fistula of larynx');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (6, 'LBEL Effet Parfait Mineral Natural Skin Effect Mouse Foundation', 'Recurrent and persistent hematuria with diffuse crescentic glomerulonephritis', '€159,53', 'Tuberculosis of other specified bone, unspecified', 'Insertion of non-drug-eluting coronary artery stent(s)');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (7, 'Amoxicillin', 'Displaced oblique fracture of shaft of humerus, left arm, sequela', '€88,77', 'Closed anterior dislocation of humerus', 'Simple suture of common bile duct');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (8, 'Felbamate', 'Pneumonia due to Methicillin susceptible Staphylococcus aureus', '€181,72', 'Accident to watercraft causing submersion injuring dockers, stevedores', 'Lysis of intraluminal adhesions of vagina');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (9, 'Levothyroxine Sodium', 'Smith''s fracture of right radius, subsequent encounter for open fracture type I or II with malunion', '€50,60', 'Syphilitic ruptured cerebral aneurysm', 'Other and unspecified segmental resection of lung');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (10, '', 'Major laceration of unspecified innominate or subclavian vein, subsequent encounter', '€179,39', 'Acute poliomyelitis, unspecified, poliovirus type III', 'Arthrotomy for removal of prosthesis without replacement, elbow');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (11, 'OXYCODONE AND ACETAMINOPHEN', 'Other fracture of shaft of humerus', '€112,32', 'Other ill-defined heart diseases', 'Microscopic examination of specimen from eye, parasitology');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (12, 'Enoxaparin Sodium', 'Displaced fracture of left radial styloid process, sequela', '€193,90', 'Closed fractures involving skull or face with other bones with subarachnoid, subdural, and extradural hemorrhage, with loss of consciousness of unspecified duration', 'Manual rupture of joint adhesions');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (13, 'Levetiracetam', 'Unspecified nonsuppurative otitis media, bilateral', '€55,30', 'Closed fracture of vault of skull with subarachnoid, subdural, and extradural hemorrhage, with prolonged [more than 24 hours] loss of consciousness and return to pre-existing conscious level', 'Appendicostomy');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (14, 'Dextrose', 'Other exposure to uncontrolled fire in building or structure', '€183,82', 'Pain in joint, multiple sites', 'Non-invasive mechanical ventilation');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (15, 'Lorazepam', 'Unspecified superficial injury of unspecified knee, initial encounter', '€119,08', 'Other disorders of lactation, delivered, with or without mention of antepartum condition', 'Insertion of therapeutic device into uterus');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (16, 'Ben E. Keith', 'Subcutaneous fat necrosis due to birth injury', '€181,08', 'Fetal conjoined twins, antepartum condition or complication', 'Partial shoulder replacement');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (17, 'SOLU-MEDROL', 'Thrombosis due to nervous system prosthetic devices, implants and grafts, initial encounter', '€168,28', 'Accident to powered aircraft at takeoff or landing injuring other person', 'Urinary manometry');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (18, 'Captopril', 'Other mechanical complication of other gastrointestinal prosthetic devices, implants and grafts, subsequent encounter', '€68,74', 'Tarsal tunnel syndrome', 'Laparoscopic lysis of adhesions of ovary and fallopian tube');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (19, 'HYDROXYUREA', 'Type III traumatic spondylolisthesis of seventh cervical vertebra, initial encounter for open fracture', '€111,82', 'Other specified family circumstances', 'Skeletal x-ray of elbow and forearm');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (20, 'Fluoxetine', 'Passenger on bus injured in collision with other nonmotor vehicle in nontraffic accident, sequela', '€75,78', 'Pneumonia due to adenovirus', 'Incision of pilonidal sinus or cyst');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (21, 'Mephyton', 'Displaced fracture of left tibial tuberosity, subsequent encounter for open fracture type I or II with malunion', '€63,64', 'Acute post-thoracotomy pain', 'Percutaneous angioscopy');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (22, 'Rescue', 'Low vision, right eye, normal vision left eye', '€59,35', 'Enthesopathy of hip region', 'Insertion of bone growth stimulator, femur');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (23, 'Atomoxetine hydrochloride', 'Sprain of unspecified sternoclavicular joint, subsequent encounter', '€135,74', 'Nonunion of fracture', 'Retroperitoneal fistulogram');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (24, 'Calcipotriene and Betamethasone Dipropionate', 'Poisoning by inhaled anesthetics, accidental (unintentional)', '€109,86', 'Osteomalacia, unspecified', 'Vaccination against pertussis');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (25, 'ReVive Fermitif Neck Renewal SPF 15', 'Drug or chemical induced diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema, left eye', '€58,91', 'Open fracture of shaft of humerus', 'Enucleation of eyeball with other synchronous implant');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (26, 'lansoprazole', 'Nondisplaced spiral fracture of shaft of unspecified tibia, subsequent encounter for open fracture type I or II with malunion', '€71,67', 'Centric occlusion maximum intercuspation discrepancy', 'Laparoscopic removal of gastric restrictive device(s)');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (27, 'Rite Aid', 'Laceration of ulnar artery at wrist and hand level of right arm', '€112,96', 'Transfusion associated circulatory overload', 'Division of nerves to adrenal glands');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (28, 'Olanzapine', 'Foreign body in urethra, sequela', '€82,88', 'Drug dependence of mother, unspecified as to episode of care or not applicable', 'Arthrodesis of shoulder');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (29, 'Heparin Sodium in Sodium Chloride', 'Displaced other extraarticular fracture of unspecified calcaneus', '€85,92', 'Myogenic ptosis', 'Noninvasive programmed electrical stimulation [NIPS]');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (30, 'Phenobarbital', 'Fracture of alveolus of mandible, unspecified side, subsequent encounter for fracture with routine healing', '€54,25', 'Conduct disorder, childhood onset type', 'Excision of other minor lesion of eyelid');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (31, 'Nitrous Oxide', 'Other specified injury of posterior tibial artery, unspecified leg, initial encounter', '€75,71', 'Acute alcoholic intoxication in alcoholism, continuous', 'Creation of conduit between right ventricle and pulmonary artery');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (32, 'Delsym', 'Other spondylosis with myelopathy, lumbar region', '€89,04', 'Pneumonitis due to inhalation of food or vomitus', 'Infusion of vasopressor agent');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (33, 'Enoxaparin Sodium', 'Contusion of right lower leg, subsequent encounter', '€177,60', 'Rupture of chordae tendineae', 'Other operations on joint structures');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (34, 'Sugar Free Cherry Herb Throat Drops', 'Periprosthetic fracture around internal prosthetic right ankle joint, subsequent encounter', '€71,36', 'Meningococcal infection, unspecified', 'Other operations on salivary gland or duct');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (35, 'Terazosin', 'Passenger in heavy transport vehicle injured in collision with other nonmotor vehicle in traffic accident', '€122,42', 'Other and unspecified vaccines and biological substances causing adverse effects in therapeutic use', 'Suprapubic prostatectomy');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (36, 'Nortriptyline Hydrochloride', 'Major laceration of femoral vein at hip and thigh level, right leg, sequela', '€53,31', 'Other vesicoureteral reflux with reflux nephropathy NOS', 'Other suture of muscle or fascia');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (37, 'AFRICAN SEA-COCONUT', 'Carcinoma in situ of skin of scalp and neck', '€180,28', 'Other inflammatory and immune myopathies, NEC', 'Trabeculotomy ab externo');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (38, 'Losartan Potassium and Hydrochlorothiazide', 'Poisoning by, adverse effect of and underdosing of expectorants', '€179,41', 'Other acute and subacute respiratory conditions due to fumes and vapors', 'Bursectomy of hand');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (39, 'calcium antacid', 'Other bursitis of knee', '€52,77', 'External hemorrhoids with other complication', 'Cisternal puncture');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (40, 'quetiapine fumarate', 'Toxic effect of venom of tarantula, assault, subsequent encounter', '€137,87', 'Screening for chemical poisoning and other contamination', 'Keratoprosthesis');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (41, 'Dexamethasone Sodium Phosphates', 'Asphyxiation due to smothering in furniture, intentional self-harm, initial encounter', '€160,55', 'Accessory carpal bones', 'Incision of vessel, other vessels of head and neck');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (42, 'Blister Blaster', 'Perforation due to foreign body accidentally left in body following heart catheterization, subsequent encounter', '€81,61', 'Other specified congenital anomalies', 'Incision of pineal gland');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (43, 'Advanced DNA Medicated Collection Kit II', 'Osteitis deformans of other bones', '€151,76', 'Open fracture of unspecified part of tibia alone', 'Removal of pyelostomy and nephrostomy tube');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (44, 'ZYNCOF', 'Posterior dislocation of left humerus, initial encounter', '€147,39', 'Peripheral T cell lymphoma, intra-abdominal lymph nodes', 'Repair of esophageal fistula, not elsewhere classified');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (45, 'all day pain relief', 'Other nondisplaced fracture of lower end of right humerus, subsequent encounter for fracture with delayed healing', '€186,15', 'Other open skull fracture without mention of intracranial injury, with brief [less than one hour] loss of consciousness', 'Open biopsy of stomach');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (46, 'Bellagio Sunscreen SPF 45', 'Nondisplaced fracture of olecranon process with intraarticular extension of left ulna, subsequent encounter for closed fracture with delayed healing', '€124,80', 'Delirium due to conditions classified elsewhere', 'Endoscopy of small intestine through artificial stoma');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (47, 'Crest Pro-Health', 'Other transitory electrolyte disturbances of newborn', '€111,16', 'Traumatic arthropathy, shoulder region', 'Cricopharyngeal myotomy');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (48, 'TAMSULOSIN HYDROCHLORIDE', 'Unspecified fracture of lower end of unspecified tibia, subsequent encounter for open fracture type I or II with delayed healing', '€156,20', 'Other anterior horn cell diseases', 'Formation of other cutaneous ureterostomy');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (49, 'Virotox', 'Laceration of dorsal vein of right foot', '€190,31', 'Hodgkin''s disease, lymphocytic-histiocytic predominance, intra-abdominal lymph nodes', 'Other diagnostic procedures on penis');
insert into Products (ID, Name, Description, Price, Remarks, Category) values (50, 'PCXX ONE MINTE GEL ROOTBEER', 'Corrosion of unspecified degree of unspecified foot', '€90,07', 'Schwannomatosis', 'Ligation of thoracic duct');
